# Generated by Django 6.0.1 on 2026-01-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=10)),
                ('total_inflow', models.FloatField()),
                ('total_outflow', models.FloatField()),
                ('average_balance', models.FloatField()),
                ('loan_emi', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('revenue', models.FloatField()),
                ('expenses', models.FloatField()),
                ('assets', models.FloatField()),
                ('liabilities', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GSTRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(max_length=15)),
                ('period', models.CharField(max_length=10)),
                ('total_sales', models.FloatField()),
                ('total_tax_paid', models.FloatField()),
                ('filing_status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
