# Generated by Django 6.0.1 on 2026-02-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
