# Generated by Django 6.0.1 on 2026-02-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingesteddocument',
            name='parsed_data',
            field=models.JSONField(default=dict),
        ),
    ]
