# Generated by Django 6.0.1 on 2026-02-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_ingesteddocument_parsed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingesteddocument',
            name='detected_type',
            field=models.CharField(choices=[('BANK', 'Bank Statement'), ('GST', 'GST Return'), ('PDF', 'PDF Document'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
    ]
