# Generated by Django 6.0.1 on 2026-02-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_alter_ingesteddocument_detected_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingesteddocument',
            name='category',
            field=models.CharField(choices=[('FIN', 'Financial Statement'), ('BANK', 'Bank Statement'), ('GST', 'GST Return')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingesteddocument',
            name='document_type',
            field=models.CharField(choices=[('PL', 'Profit & Loss'), ('BS', 'Balance Sheet'), ('CF', 'Cash Flow'), ('BANK', 'Bank Statement'), ('GSTR1', 'GSTR-1'), ('GSTR3B', 'GSTR-3B')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingesteddocument',
            name='detected_type',
            field=models.CharField(choices=[('BANK', 'Bank Statement'), ('GST', 'GST Return'), ('PDF', 'PDF'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
    ]
