class RecommendationCategory:
    COST_OPTIMIZATION = "COST_OPTIMIZATION"
    CASHFLOW_IMPROVEMENT = "CASHFLOW_IMPROVEMENT"
    GST_COMPLIANCE = "GST_COMPLIANCE"
    FINANCIAL_STABILITY = "FINANCIAL_STABILITY"
    CREDIT_READINESS = "CREDIT_READINESS"
