# Generated by Django 6.0.1 on 2026-02-05 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_credits', models.FloatField(blank=True, null=True)),
                ('total_debits', models.FloatField(blank=True, null=True)),
                ('net_cash_flow', models.FloatField(blank=True, null=True)),
                ('expense_ratio', models.FloatField(blank=True, null=True)),
                ('cashflow_volatile', models.BooleanField(default=False)),
                ('taxable_value', models.FloatField(blank=True, null=True)),
                ('gst_paid', models.FloatField(blank=True, null=True)),
                ('expected_gst', models.FloatField(blank=True, null=True)),
                ('compliance_gap', models.FloatField(blank=True, null=True)),
                ('is_compliant', models.BooleanField(default=True)),
                ('total_assets', models.FloatField(blank=True, null=True)),
                ('total_liabilities', models.FloatField(blank=True, null=True)),
                ('savings_ratio', models.FloatField(blank=True, null=True)),
                ('current_ratio', models.FloatField(blank=True, null=True)),
                ('financial_health_score', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='api.document')),
            ],
        ),
    ]
