# Generated by Django 6.0.1 on 2026-02-03 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_alter_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=10)),
                ('total_credits', models.FloatField(default=0)),
                ('total_debits', models.FloatField(default=0)),
                ('net_cash_flow', models.FloatField(default=0)),
                ('expense_ratio', models.FloatField(default=0)),
                ('cashflow_volatile', models.BooleanField(default=False)),
                ('taxable_value', models.FloatField(default=0)),
                ('gst_paid', models.FloatField(default=0)),
                ('expected_gst', models.FloatField(default=0)),
                ('compliance_gap', models.FloatField(default=0)),
                ('is_compliant', models.BooleanField(default=True)),
                ('financial_health_score', models.IntegerField()),
                ('risk_level', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='documents.document')),
            ],
        ),
    ]
