# Generated by Django 6.0.1 on 2026-02-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentanalysis',
            name='document_type',
            field=models.CharField(choices=[('BANK', 'Bank Statement'), ('GST', 'GST Document'), ('FIN', 'Financial Document')], max_length=10),
        ),
    ]
