# Generated by Django 6.0.1 on 2026-02-04 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_documentanalysis_document_type'),
        ('documents', '0002_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentanalysis',
            name='current_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentanalysis',
            name='savings_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentanalysis',
            name='total_assets',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentanalysis',
            name='total_liabilities',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='compliance_gap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='document_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='expected_gst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='expense_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='financial_health_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='gst_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='net_cash_flow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='risk_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='taxable_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='total_credits',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentanalysis',
            name='total_debits',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
