# Generated by Django 6.0.1 on 2026-02-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeAnalysisState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credits', models.FloatField(default=0)),
                ('total_debits', models.FloatField(default=0)),
                ('net_cash_flow', models.FloatField(default=0)),
                ('closing_balance', models.FloatField(default=0)),
                ('expense_ratio', models.FloatField(default=0)),
                ('savings_ratio', models.FloatField(default=0)),
                ('cashflow_volatile', models.BooleanField(default=False)),
                ('taxable_value', models.FloatField(default=0)),
                ('gst_paid', models.FloatField(default=0)),
                ('expected_gst', models.FloatField(default=0)),
                ('payment_ratio', models.FloatField(default=0)),
                ('compliance_gap', models.FloatField(default=0)),
                ('is_compliant', models.BooleanField(default=False)),
                ('financial_health_score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
