# Generated by Django 6.0.1 on 2026-02-01 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='financial_documents/')),
                ('category', models.CharField(choices=[('FIN', 'Financial Statement'), ('BANK', 'Bank Statement'), ('GST', 'GST Return')], max_length=10)),
                ('document_type', models.CharField(max_length=20)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('source', models.CharField(blank=True, max_length=100)),
                ('file_type', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
