# Generated by Django 6.0.1 on 2026-02-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdocument',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialdocument',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='financialdocument',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('XLSX', 'XLSX')], max_length=10),
        ),
        migrations.AlterField(
            model_name='financialdocument',
            name='period_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialdocument',
            name='period_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
