# Generated by Django 6.0.1 on 2026-01-31 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    migrations.AddField(
        model_name='financialdocument',
        name='category',
        field=models.CharField(
            choices=[
                ('FIN', 'Financial Statement'),
                ('BANK', 'Bank Statement'),
                ('GST', 'GST Return'),
            ],
            max_length=10,
            null=True,
            blank=True,
        ),
    ),
    migrations.AddField(
        model_name='financialdocument',
        name='document_type',
        field=models.CharField(
            max_length=20,
            null=True,
            blank=True,
        ),
    ),
    migrations.AddField(
        model_name='financialdocument',
        name='period_from',
        field=models.DateField(
            null=True,
            blank=True,
        ),
    ),
    migrations.AddField(
        model_name='financialdocument',
        name='period_to',
        field=models.DateField(
            null=True,
            blank=True,
        ),
    ),
    migrations.AddField(
        model_name='financialdocument',
        name='source',
        field=models.CharField(
            max_length=100,
            blank=True,
        ),
    ),
    migrations.AlterField(
        model_name='financialdocument',
        name='file_type',
        field=models.CharField(max_length=10),
    ),
    migrations.AlterField(
        model_name='financialdocument',
        name='user',
        field=models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            to=settings.AUTH_USER_MODEL,
        ),
    ),
]
