# Generated by Django 6.0.1 on 2026-02-01 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_financialdocument_processed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentParseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.IntegerField(blank=True, null=True)),
                ('columns', models.JSONField(blank=True, null=True)),
                ('text_length', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parse_result', to='documents.financialdocument')),
            ],
        ),
    ]
