# Generated by Django 6.0.1 on 2026-02-03 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_alter_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLInference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('features', models.JSONField()),
                ('probability', models.FloatField(null=True)),
                ('predicted_risk', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_inferences', to='documents.document')),
            ],
        ),
    ]
